apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-wrapper
  annotations: {}
  name: helm-wrapper
#  namespace: kube-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: helm-wrapper
  type: ClusterIP